/*
 * Copyright (c) 2002 Scott Clee (Scott_Clee@uk.ibm.com), Software Engineer, IBM
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package tetrisbean;

/**
 * This interface allows an object to listen for
 * GameEvent's which are generated by a TetrisGame
 * everytime a game is started or stopped.
 * 
 * @author Scott Clee
 */
public interface GameListener
{
    /**
     * This method is invoked everytime a TetrisGame
     * is started or stopped.
     * 
     * @param event a GameEvent
     */
    public void gameChange(GameEvent event);
}
